#!/usr/bin/env python3

import os
from anki.storage import Collection
import ffmpeg
import argparse
cwd = os.getcwd()

parser = argparse.ArgumentParser(description='Import audio files to anki and speed them up.')

parser.add_argument('--audio_files_path', required=True)
parser.add_argument('--anki_user_path', nargs='?', default='/home/{user}/.local/share/Anki2/{user}'.format(user=os.environ.get('USER')))
parser.add_argument('--speed', nargs='?', default='1.0')

args = parser.parse_args()

anki_user_path = args.anki_user_path
audio_files_path = args.audio_files_path
speed = args.speed

# load anki collection and deck
anki_user_collection_path = os.path.join(anki_user_path, "collection.anki2")
col = Collection(anki_user_collection_path, log=True)

# sets current deck and note type == model 
deck_id = col.decks.id("main")  # creates deck if not exists
model_id = col.models.byName('Basic')['id']  # model = note type

# specifies the id of the deck that cards are added to by default
model = col.models.get(model_id)
model['did'] = deck_id 

os.chdir(cwd)

for input_file_name in os.listdir(audio_files_path):
    if input_file_name.endswith(".mp3"):
        print(input_file_name)
        # setup path names
        input_file_path = os.path.join(audio_files_path, input_file_name)

        converted_output_file_name = '{}_speeded_up.mp3'.format(
            input_file_name[:-4])
        converted_file_path = os.path.join(
            audio_files_path, converted_output_file_name)

        output_file_path = os.path.join(
            anki_user_path, 'collection.media', converted_output_file_name)

        # speed up audio files
        stream = ffmpeg.input(input_file_path)
        stream = ffmpeg.filter(stream, 'atempo', speed)
        stream = ffmpeg.output(stream, converted_file_path)
        stream = ffmpeg.overwrite_output(stream)
        ffmpeg.run(stream)

        # move to audio file to anki
        fname = col.media.addFile(converted_file_path)
        # create corresponding anki note for audio file
        note = col.newNote()
        note.fields[0] = fname[:-4]
        note.fields[1] = u'[sound:%s]' % fname
        col.addNote(note)

        # clean source
        os.remove(input_file_path)
        os.remove(converted_file_path)

col.close()
